// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHD8kw_Bixu-BZKaR7smhDpc1L-vXISqw',
    appId: '1:944826110823:web:ec6f219a44f4832fba55c2',
    messagingSenderId: '944826110823',
    projectId: 'finstat-dev',
    authDomain: 'finstat-dev.firebaseapp.com',
    storageBucket: 'finstat-dev.firebasestorage.app',
    measurementId: 'G-8QNFGJ8P13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGObQZUDUn0G1HCuALUNX1WWcc-MWBjo',
    appId: '1:944826110823:android:e690728532fd6abdba55c2',
    messagingSenderId: '944826110823',
    projectId: 'finstat-dev',
    storageBucket: 'finstat-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLWKL9Uhq6DCFDp90WHuJkL4TFk6IbobQ',
    appId: '1:944826110823:ios:8fc47e367b4266eeba55c2',
    messagingSenderId: '944826110823',
    projectId: 'finstat-dev',
    storageBucket: 'finstat-dev.firebasestorage.app',
    iosBundleId: 'com.brb.finstat.dev',
  );
}
