// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoIYRP59BEr0L9EVrtqXTwg53ZOlQG0D4',
    appId: '1:150893818281:web:8d9d7360b10c1ad8c614b8',
    messagingSenderId: '150893818281',
    projectId: 'finstat-stg',
    authDomain: 'finstat-stg.firebaseapp.com',
    storageBucket: 'finstat-stg.firebasestorage.app',
    measurementId: 'G-XHYBSGNVGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJrcHQzRqA5GoVOVh54xDaDmzJtQKGD4',
    appId: '1:150893818281:android:b0581401eeb39f88c614b8',
    messagingSenderId: '150893818281',
    projectId: 'finstat-stg',
    storageBucket: 'finstat-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NkA9tDJKbVuHEQOAVqYWPbU-5ZVWES4',
    appId: '1:150893818281:ios:50c040e5b3713eb0c614b8',
    messagingSenderId: '150893818281',
    projectId: 'finstat-stg',
    storageBucket: 'finstat-stg.firebasestorage.app',
    iosBundleId: 'com.brb.finstat.stg',
  );
}
