// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzg2RAT0dxPw04768Hf4czGUBuSag48c8',
    appId: '1:447645597381:web:28a192b06fee47f5d0faac',
    messagingSenderId: '447645597381',
    projectId: 'finstat-prod',
    authDomain: 'finstat-prod.firebaseapp.com',
    storageBucket: 'finstat-prod.firebasestorage.app',
    measurementId: 'G-M568JGPTCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRp0mbKPzTf_b1EAmT6Y-jpBEqkoVqpQs',
    appId: '1:447645597381:android:5f5c88a9ebfe6b70d0faac',
    messagingSenderId: '447645597381',
    projectId: 'finstat-prod',
    storageBucket: 'finstat-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClF65iUj0I7iFrhDHk71EnM-sGRjEet98',
    appId: '1:447645597381:ios:86083563361df9ebd0faac',
    messagingSenderId: '447645597381',
    projectId: 'finstat-prod',
    storageBucket: 'finstat-prod.firebasestorage.app',
    iosBundleId: 'com.brb.finstat',
  );

}